name: taskforce_hrms
description: A system of human resources managment system using Flutter, Firebase and Pythin for AI.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hexcolor: ^3.0.1
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  firebase_storage: ^11.2.6
  loading_animation_widget: ^1.2.0+4
#  flutter_icon_snackbar: ^1.1.4
  shared_preferences: ^2.2.0
  file_picker: ^9.2.1
  introduction_screen: ^3.1.11
  url_launcher: ^6.1.12
  dart_secure: ^0.6.1
  image_picker: ^1.0.4
  adaptive_theme: ^3.4.1
  table_calendar: ^3.0.9
  geolocator: ^13.0.3
  toastification: ^3.0.2
  firebase_in_app_messaging: ^0.7.4+12


  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  local_auth: ^2.1.6
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/TFLogo.jpg"

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/components/
    - assets/fonts/
    - assets/homeTabs/
    - assets/logo/



  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
flutter_intl:
  enabled: true